---
title: "About Me"
---

Since 7th grade, when I joined the Télémaque mentoring project, opportunities have multiplied, and my curiosity has grown. Coming from a disadvantaged neighborhood with non-graduate parents, it became my ambition to combat social inequalities by developing my passion for education and realizing the impact I can have on the world. It was a great pleasure for me to take part in the cultural and professional opening activities offered by the association. The Télémaque Institute has supported me beyond the unequal cycle in which I was trapped, where my geographical situation shaped the quality of my education.

In 10th grade, the real turning point was participating in a webinar with a Télémaque partner. I was introduced to United World Colleges (UWC), and after a long selection process, I left for UWC Maastricht, an international high school in the Netherlands that shapes future dreamers and "changemakers" ready to have an impact on the world of tomorrow. The full scholarship of €58,000 offered me the opportunity to access a unique education in the International Baccalaureate, surrounded by people from over a hundred different nationalities. This two-year experience encouraged me to take multiple initiatives: I contributed to campus life with Spirit Team; discussed the impacts of colonialism by leading the Decolonise Club; offered a learning environment to students through the Coding Club; created an entrepreneurial project to deconstruct beauty standards with Project Beauty, and much more. I am constantly learning from others and am fortunate to develop my passions while exploring new ones. I am grateful to have been able to take these initiatives while focusing on my studies and fully enjoying my UWC experience without having to worry about money.

Thanks to these experiences, I was accepted into a recognized higher education institution in the United States, Macalester College, where I have the opportunity to continue exploring my passions and developing my skills on a daily basis. My university scholarship offer for my second year amounts to $78,852, with a maximum of $4,290 for working during the year (50% to pay tuition fees and 50% for my pocket money). The $83,219 tuition fees are only for the 2023-2024 academic year and will certainly increase for the upcoming academic year. Assuming that the fees remain unchanged, there is still a difference of $2,222, and the plane tickets for the major winter and summer holidays to pay for. Despite the generous scholarship offered by the university, I am unable to cover the remaining tuition fees. Pursuing a degree in computer science at Macalester College to become an Artificial Intelligence engineer will give me the opportunity to change the world of tomorrow and to be able, later on, to give the same opportunities to young people from a similar background, following the support I received from Télémaque. This is why I am requesting financial assistance from you to help me pursue my university studies. I am convinced that this education will be a valuable investment for my future and will allow me to represent abroad the values and impact of the Télémaque mission.
