[build]
command = "curl -fsSL https://quarto.org/download/latest/quarto-linux-amd64.tar.gz | tar -xz -C /usr/local/bin && quarto render"
publish = "docs"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200