[build]
command = "curl -fsSL https://quarto.org/download/latest/quarto-linux-amd64.deb -o quarto.deb && sudo dpkg -i quarto.deb && quarto render"
publish = "docs"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200