---
title: "Relevant Courses"
editor: visual
---

### Code Institute 5 Day Coding Challenge

This coding bootcamp is to learn the basics of HTML, CSS & JavaScript. Through building a Webpage participants delve into styling with CSS, HTML 5 & The Semantic Web, Responsive Design and JavaScript basics. On completion of this coding course, a certificate of completion will be received.

## COMP 127 - Object-Oriented Programming and Abstraction

This course is an introduction to the building blocks of software design: abstraction, decomposition, and encapsulation. Using object-oriented programming in Java, we create graphics, games, and simulations, and explore natural language processing. Topics include: classes, objects, polymorphism, inheritance, testing, refactoring, events, closures, streams, immutability, parallel programming, and version control. The course culminates in a student-designed project. There is a required 1.5 hour laboratory section associated with this course.

## COMP 123 - Core Concepts in Computer Science

This course introduces the field of computer science, including central concepts such as the design and implementation of algorithms and programs, testing and analyzing programs, the representation of information within the computer, and the role of abstraction and metaphor in computer science. The exploration of these central ideas will draw examples from a range of application areas including multimedia processing, turtle graphics, and text processing. Course work uses the Python programming language.

## CS50x - Introduction to Computer Science

CS50x is Harvard University's introduction to the intellectual enterprises of computer science and the art of programming for majors and non-majors alike, with or without prior programming experience. An entry-level course taught by David J. Malan, CS50x teaches students how to think algorithmically and solve problems efficiently. Topics include abstraction, algorithms, data structures, encapsulation, resource management, security, software engineering, and web development. Languages include C, Python, SQL, and JavaScript plus CSS and HTML. Problem sets inspired by real-world domains of biology, cryptography, finance, forensics, and gaming.

Students who earn a satisfactory score on 9 problem sets (i.e., programming assignments) and a final project are eligible for a certificate in this self-paced course.

**Outcomes of this course:**

-   A broad and robust understanding of computer science and programming

-   How to think algorithmically and solve programming problems efficiently

-   Concepts like abstraction, algorithms, data structures, encapsulation, resource management, security, software engineering, and web development

-   Familiarity with a number of languages, including C, Python, SQL, and JavaScript plus CSS and HTML

-   How to engage with a vibrant community of like-minded learners from all levels of experience

-   How to develop and present a final programming project to your peers

-   Harvard University certificate upon completion


